FIX_Ethtool_filters
intel/afxdp-plugins-for-kubernetes pull request #63
Opened 2023-07-05 09:48 UTC by patrickog11

Ethtool feature moved to CNI where filters now assigned via the networkAttachmentDefinition file. DeviceFile feauture removed.

2023-07-05 10:42 UTC, garyloug requested changes

2023-07-05 10:42 UTC, garyloug commented on internal/cni/cni.go
> +	//"github.com/intel/afxdp-plugins-for-kubernetes/internal/tools"
Remove commented code

2023-07-05 10:42 UTC, garyloug commented on internal/cni/cni.go
> +		if ethInstalled {
might be nicer here to first check if the NAD contains ethtool cmds and then check if ethtool is installed
i.e. kind of swap lines 210 and 213

If the user has ethtool cmds in the NAD and the host can't provide it, then we can log an error

2023-09-20 10:15 UTC, maryamtahhan approved these changes

2023-10-12 10:49 UTC, garyloug approved these changes

2023-10-12 10:50 UTC, merged