C library wrapper
intel/afxdp-plugins-for-kubernetes pull request #71
Opened 2023-08-01 15:28 UTC by phansGithub

This is to wrap the go client library for c using cgo, however there are two commits caused by syncing the fork, so maybe I can try squashing the commits together because one of the commits is just a merge.

2023-08-02 11:14 UTC, garyloug requested changes

2023-08-03 08:58 UTC, phansGithub commented on pkg/cclient/README.md
> +## Next steps
Apologies about the extern definitions, those were artefacts I forgot to remove when I tried to make a header file for the c library before I knew that cgo can take care of it and we could just import the generated header file.

2023-08-03 13:27 UTC, phansGithub commented
Quick thing: The changes to the UDS Server seem to have been overwritten by my first force-push, I think it's because the branch I was working on didn't branch off of main before I changed the UDS server

2023-09-20 10:29 UTC, maryamtahhan requested changes

2023-09-20 10:29 UTC, maryamtahhan commented on pkg/cclient/README.md
> +## Creating the .h and the .so files:
```suggestion
## Creating the shared library and header files:
```

2023-09-20 10:29 UTC, maryamtahhan commented on pkg/cclient/README.md
> +
only need one line not 2 - I think this should be flagged by the markdown linter

2023-09-20 10:29 UTC, maryamtahhan commented on pkg/cclient/README.md
> +```go build -o lib_udsclient.so -buildmode=c-shared cclient.go```
```suggestion
```cmd 
go build -o lib_udsclient.so -buildmode=c-shared cclient.go
```
```
Again I'm surprised the linter didn't flag this

2023-09-20 10:29 UTC, maryamtahhan commented on pkg/cclient/README.md
> +## Creating the .h and the .a files:
```suggestion
## Creating the static library and header files:
```

2023-09-20 10:29 UTC, maryamtahhan commented on pkg/cclient/README.md
> +```go build -o lib_udsclient.a -buildmode=c-archive ./cclient.go```
```suggestion
```cmd
go build -o lib_udsclient.a -buildmode=c-archive ./cclient.go
```
```

2023-09-20 10:29 UTC, maryamtahhan commented on pkg/cclient/README.md
> +After creating the .h and/or the .a and the .o files as described in the previous steps,
```suggestion
After creating the library and header files as described in the previous steps,
```

2023-09-20 10:29 UTC, maryamtahhan commented on pkg/cclient/README.md
> +This returns the version of our handshake on your local machine/client.
```suggestion
This returns the version of the handshake on your local machine/client.
```

2023-09-20 10:29 UTC, maryamtahhan commented on pkg/cclient/README.md
> +This returns the version of our handshake on the server/host.
```suggestion
This returns the version of the handshake on the server/host.
```

2023-09-20 10:29 UTC, maryamtahhan commented on pkg/cclient/README.md
> +``` char* GetUdsClientVersion()```
```suggestion
``` c
char* GetUdsClientVersion()
```
```

and the same for all the function signatures below Or make them a header

### char* GetUdsClientVersion()

2023-09-20 10:29 UTC, maryamtahhan commented on pkg/cclient/README.md
> +This requests an Xsk map Fd for a specifed device.
```suggestion
This requests an xskmap Fd for a specified device.
```

2023-09-20 10:29 UTC, maryamtahhan commented on pkg/cclient/README.md
> +so that the connection to the Uds can be cleaned up.
```suggestion
so that the connection to the UDS can be cleaned up.
```

2023-09-20 10:29 UTC, maryamtahhan commented on pkg/cclient/cclient.go
> +GetClientVersion is an exported version for c of goclient's GetClientVersion()
```suggestion
GetClientVersion is an exported version for c of the goclient GetClientVersion()
```

same throughout the file... I don't think `goclient's` is grammatically correct

2023-09-20 10:29 UTC, maryamtahhan commented on pkg/cclient/cclient.go
> +	fdVal, function, err := goclient.RequestXSKmapFD(C.GoString(device))
should you check device isn't Nil before passing it along to RequestXSKmapFD

2023-09-20 10:29 UTC, maryamtahhan commented on pkg/cclient/cclient.go
> +	function, err := goclient.RequestBusyPoll(int(busyTimeout), int(busyBudget), int(fd))
should probably do some param error checking before calling RequestBusyPoll

2023-10-12 10:52 UTC, garyloug approved these changes

2023-10-12 10:53 UTC, merged